### ISSUE TITLE
MySQL connecting problem

### ISSUE THREAD

**Issue by Pacific73** [langcog/wordbankr#11]
I've tried to install this package correctly with Brew on my Mac OS(if everything goes well). 
When I tried the code like what in the tutorial such as `english_ws_admins <- get_administration_data("English", "WS")` on the R platform, an error appears as follows:
`Auto-disconnecting mysql connection (0, 1)`
`Joining, by = "momed_id"`
`Auto-disconnecting mysql connection (0, 0)`

I've been noticed that a red block is on the "analyses" page with "**WARNING: Your Shiny Server license expired on March 22, 2017.**" on it(http://wordbank.stanford.edu/analyses?name=vocab_norms). 
So I wondered whether this can cause the connection problem? Or I just didn't use the function right?

**Comment by mcfrank** [comment]
thanks for the report. 

we will check into the server licensing issue. 

that "auto-disconnecting" message is a notification that the dplyr package returns. did you get data in the `english_ws_admins` data frame? that command produces the same red notifications but does return data for me.

**Comment by Pacific73** [comment]
Oh, I got it.

I thought it was a mistake that stopped getting data from the remote database. But I did get the data and I ignored it.

Thanks for answering in a short time!
