### ISSUE TITLE
match_crossling_items fails

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbankr#15]
`crossling_words <- match_crossling_items(unilemmas = c("hat", "nose"))` fails with error 

> Error in filter_impl(.data, quo) : 
>   Argument 2 filter condition does not evaluate to a logical vector

this may be a version thing but I think I'm up to date on everything?

**Comment by daniellekellier** [comment]
How strange! Did you install wordbankr via CRAN or GitHub?

**Comment by mcfrank** [comment]
I reinstalled via github, actually.

**Comment by daniellekellier** [comment]
Should work now!
