### ISSUE TITLE
server connection modes

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbankr#2]
The old data loading script had three server connection modes: local, prod, and dev, with prod confusingly being server that runs shiny, not the one that runs django (yeah, we have two separate copies of the database set up... gross...). Do we want to not include dev server connection in the package? Have it require an actual password?

**Comment by mcfrank** [comment]
that database thing is gross, I agree... it's an optimization thing, right, so that shiny gets its own local copy. 

+1 for dev should require password.

**Comment by dyurovsky** [comment]
Seconded, definitely don't want people connecting to dev without a
password, and we should make prod the default.

Dan

**Comment by mikabr** [comment]
Is "prod" the right label for it?

**Comment by mcfrank** [comment]
dev and prod seem reasonable in contrast to one another, but maybe we should just make it a default that you generally don't specify unless you want dev? as a habitual argument it's probably a little baffling.
