### ISSUE TITLE
Failed to connect to database error

### ISSUE THREAD

**Issue by hilary-rose** [langcog/wordbankr#26]
Hi there, I am getting an error today in a script that worked without issue up until now. Here is the code:

`get_item_data(language = "English (American)", "WS") %>% 
  filter(type == "word") %>%  
  select(definition, num_item_id) %>%
  arrange(definition)  %>%
  #filter(!str_detect(definition, "babysitter's"))%>%
  mutate(id = row_number())`

And the error message:

`Error in .local(drv, ...) : 
  Failed to connect to database: Error: Access denied for user 'wordbank'@'75.98.19.151' (using password: YES)`

Do you have any advice about how to fix this? It seems to have to do with accessing a MySQL database, but I'm not sure what to do about it. Thank you!

**Comment by mikabr** [comment]
hi hilary, we were having some connectivity issues but they should be resolved now. does your script run now?

**Comment by hilary-rose** [comment]
Thank you! The script does run now, I'll close this issue :)
